# Generated by Django 2.2.16 on 2023-04-05 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='slag',
            new_name='slug',
        ),
    ]
